name = input("What is your name?:")
print(name)
food = input("What  is your favorite food?:")
print(f"Your favourite food is {food}. ")
music = input("What is your favorite song?:")
print(f"Your favourite song is {music}.")
livingPlace = input("Where do you live?:")
print(f"You live in the {livingPlace}.")
print("You rock!!! 🚀 Thank you for your time and have a great day!")